/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-02-09 06:33:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/index.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Sunflower:300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>HOLLYS Coffee</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <div class=\"headerInner\">\r\n");
      out.write("                <h1 class=\"logo\"><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/logo.gif\" alt=\"HOLLYS COFFEE\"></a></h1>\r\n");
      out.write("                <ul class=\"util\">\r\n");
      out.write("                    <li><a href=\"\">멤버십 로그인</a></li>\r\n");
      out.write("                    <li><a href=\"\">멤버십 가입</a></li>\r\n");
      out.write("                    <li><a href=\"\">고객센터</a></li>\r\n");
      out.write("                    <li><a href=\"\">English</a></li>\r\n");
      out.write("                    <li><a href=\"\">中文</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul class=\"quickBanner\">\r\n");
      out.write("                    <li class=\"btn_franchise\"><a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/gnb_smenu01.png\" alt=\"Franchise\"></a></li>\r\n");
      out.write("                    <li><a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/gnb_smenu02_2.gif\" alt=\"Academy\"></a></li>\r\n");
      out.write("                    <li><a href=\"\"><img class=\"img_business\" src=\"");
      out.print(request.getContextPath());
      out.write("/image/gnb_smenu04.gif\" alt=\"business\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul class=\"gnb\">\r\n");
      out.write("                    <li><a href=\"\">Menu</a></li>\r\n");
      out.write("                    <li><a href=\"\">HOLLYS Mall</a></li>\r\n");
      out.write("                    <li><a href=\"\">Membership</a></li>\r\n");
      out.write("                    <li><a href=\"\">HOLLYS News</a></li>\r\n");
      out.write("                    <li><a href=\"\">Store</a></li>\r\n");
      out.write("                    <li><a href=\"\">HOLLYS is</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main_visual_slide_img\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/main_image2.jpg\" alt=\"\"></li>\r\n");
      out.write("                <!-- Javascript로 Image slide 만들 예쩡  \r\n");
      out.write("                <li><img src=\"img/main_image3.jpg\" alt=\"\"></li>\r\n");
      out.write("                <li><img src=\"img/main_image.jpg\" alt=\"\"></li> \r\n");
      out.write("                --> \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"contents_wrap\">\r\n");
      out.write("            <div class=\"contents_top_wr\">\r\n");
      out.write("                <div class=\"wr_mainList\">\r\n");
      out.write("                    <div class=\"list_le\">\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/Franchise_main_top.gif\" alt=\"\" style=\"padding-left: 19px;\">\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/Franchise_main.gif\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"list_center\">\r\n");
      out.write("                        <div class=\"list_center_top\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/mall_tit.gif\" alt=\"\">\r\n");
      out.write("                            <p>할리스커피의 다양한 상품들을 온라인에서도 만나보세요.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list_center_left\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/coffee_l.png\" alt=\"\" style=\"max-width: 60%;\">\r\n");
      out.write("                            <p>리스트레또 딜라이드 R</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list_center_center\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/eggma.png\" alt=\"\" style=\"max-width: 60%;\">\r\n");
      out.write("                            <p>에그마요</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list_center_right\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/chia.png\" alt=\"\" style=\"max-width: 60%;\">\r\n");
      out.write("                            <p>올리브 베이컨 치아바타</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"list_ri\">\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/Find_main_top.gif\" alt=\"\" style=\"padding-left: 19px;\">\r\n");
      out.write("                        <img src=\"");
      out.print(request.getContextPath());
      out.write("/image/Find_main.gif\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"wr_mainList02\">\r\n");
      out.write("                    <div class=\"main_02_left\">\r\n");
      out.write("                        <a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/img_banner_membership.jpg\" alt=\"\" style=\"max-width: 100%;\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"main_02_center\"></div>\r\n");
      out.write("                    <div class=\"main_02_right\">\r\n");
      out.write("                        <a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/giftgift.jpg\" alt=\"\" style=\"max-width: 100%;\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"wr_mainList03\">\r\n");
      out.write("                    <ul class=\"main_03_left\">\r\n");
      out.write("                        <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/academy_tit.gif\" alt=\"\" style=\"max-width: 80%;\"></li>\r\n");
      out.write("                        <li style=\"margin-top:4px;\">할리스커피 아카데미와 함께하는 즐거운<br> 커피 여행!</li>\r\n");
      out.write("                        <li class=\"going\">바로가기</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"main_03_left_center\">\r\n");
      out.write("                        <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/b2b_tit.gif\" alt=\"\" style=\"max-width: 80%;\"></li>\r\n");
      out.write("                        <li style=\"margin-top:4px;\">할리스 F&B는 20년의 커피 노하우를 기반으로 한 할리스 B2B 솔루션을 소개합니다.</li>\r\n");
      out.write("                        <li class=\"going\">바로가기</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"main_03_right_center\">\r\n");
      out.write("                        <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/image/news_tit.gif\" alt=\"\" style=\"max-width: 80%;\"></li>\r\n");
      out.write("                        <li style=\"margin-top:4px;\">SKTelecom T멤버십 VIP</li>\r\n");
      out.write("                        <li style=\"margin-top:4px;\">LGU+ 멤버십 제휴 제외</li>\r\n");
      out.write("                        <li style=\"margin-top:4px;\">LG CNS 성과급 얼마 ? </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"main_03_right\">\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
